<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2HDr8s\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2HDr8s/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ2HDr8s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQ2HDr8s\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerQ2HDr8s\srcApp_KernelProdContainer([
    'container.build_hash' => 'Q2HDr8s',
    'container.build_id' => 'b69decd7',
    'container.build_time' => 1617290147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2HDr8s');
