<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ujzkdXH' shared service.

return $this->privates['.service_locator.ujzkdXH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'kernel' => ['services', 'kernel', 'getKernelService', false],
    'services' => ['privates', 'App\\Service\\AppServices', 'getAppServicesService', false],
], [
    'kernel' => '?',
    'services' => 'App\\Service\\AppServices',
]);
