<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Mp.4THn' shared service.

return $this->privates['.service_locator.Mp.4THn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eventdispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
    'translator' => ['services', 'translator', 'getTranslatorService', false],
], [
    'eventdispatcher' => '?',
    'translator' => '?',
]);
