<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_auto_form.form.type.auto_form_type' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/a2lix/auto-form-bundle/src/Form/Type/AutoFormType.php';
include_once \dirname(__DIR__, 4).'/vendor/a2lix/auto-form-bundle/src/Form/EventListener/AutoFormListener.php';

return $this->privates['a2lix_auto_form.form.type.auto_form_type'] = new \A2lix\AutoFormBundle\Form\Type\AutoFormType(new \A2lix\AutoFormBundle\Form\EventListener\AutoFormListener(($this->privates['a2lix_auto_form.form.manipulator.doctrine_orm_manipulator'] ?? $this->load('getA2lixAutoForm_Form_Manipulator_DoctrineOrmManipulatorService.php'))));
