<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'JMS\TranslationBundle\Controller\ApiController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/jms/translation-bundle/JMS/TranslationBundle/Controller/ApiController.php';

return $this->services['JMS\\TranslationBundle\\Controller\\ApiController'] = new \JMS\TranslationBundle\Controller\ApiController(($this->services['jms_translation.config_factory'] ?? $this->load('getJmsTranslation_ConfigFactoryService.php')), ($this->services['jms_translation.updater'] ?? $this->load('getJmsTranslation_UpdaterService.php')));
