<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.locale.simple_provider' shared service.

include_once \dirname(__DIR__, 4).'/vendor/a2lix/translation-form-bundle/src/Locale/LocaleProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/a2lix/translation-form-bundle/src/Locale/SimpleProvider.php';

return $this->privates['a2lix_translation_form.locale.simple_provider'] = new \A2lix\TranslationFormBundle\Locale\SimpleProvider($this->getParameter('a2lix_translation_form.locales'), $this->getEnv('DEFAULT_LOCALE'), $this->getParameter('a2lix_translation_form.required_locales'));
