<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_auto_form.form.manipulator.doctrine_orm_manipulator' shared service.

include_once \dirname(__DIR__, 4).'/vendor/a2lix/auto-form-bundle/src/Form/Manipulator/FormManipulatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/a2lix/auto-form-bundle/src/Form/Manipulator/DoctrineORMManipulator.php';
include_once \dirname(__DIR__, 4).'/vendor/a2lix/auto-form-bundle/src/ObjectInfo/DoctrineORMInfo.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/ClassMetadataFactory.php';

return $this->privates['a2lix_auto_form.form.manipulator.doctrine_orm_manipulator'] = new \A2lix\AutoFormBundle\Form\Manipulator\DoctrineORMManipulator(new \A2lix\AutoFormBundle\ObjectInfo\DoctrineORMInfo(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService())->getMetadataFactory()), [0 => 'id', 1 => 'locale', 2 => 'translatable']);
