<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bazinga.jstranslation.dump_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/willdurand/js-translation-bundle/Command/DumpCommand.php';

$this->services['bazinga.jstranslation.dump_command'] = $instance = new \Bazinga\Bundle\JsTranslationBundle\Command\DumpCommand(($this->services['bazinga.jstranslation.translation_dumper'] ?? $this->load('getBazinga_Jstranslation_TranslationDumperService.php')), (\dirname(__DIR__, 4).'/src'));

$instance->setName('bazinga:js-translation:dump');

return $instance;
