<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'coresphere_console.controller' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/coresphere/console-bundle/Controller/ConsoleController.php';
include_once \dirname(__DIR__, 4).'/vendor/coresphere/console-bundle/Contract/Executer/CommandExecuterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/coresphere/console-bundle/Executer/CommandExecuter.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Application.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Console/Application.php';
include_once \dirname(__DIR__, 4).'/vendor/coresphere/console-bundle/Console/ApplicationFactory.php';

$a = ($this->services['kernel'] ?? $this->get('kernel', 1));

return $this->services['coresphere_console.controller'] = new \CoreSphere\ConsoleBundle\Controller\ConsoleController(($this->services['templating'] ?? $this->load('getTemplatingService.php')), new \CoreSphere\ConsoleBundle\Executer\CommandExecuter($a), (new \CoreSphere\ConsoleBundle\Console\ApplicationFactory())->create($a), 'prod');
