<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ewz_recaptcha.form.type' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/excelwebzone/recaptcha-bundle/src/Form/Type/EWZRecaptchaType.php';
include_once \dirname(__DIR__, 4).'/vendor/excelwebzone/recaptcha-bundle/src/Locale/LocaleResolver.php';

return $this->services['ewz_recaptcha.form.type'] = new \EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType($this->getEnv('EWZ_RECAPTCHA_SITE_KEY'), true, false, new \EWZ\Bundle\RecaptchaBundle\Locale\LocaleResolver($this->getEnv('DEFAULT_LOCALE'), true, ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))), 'www.google.com');
