<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.resetting.form.factory' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Form/Factory/FactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Form/Factory/FormFactory.php';

return $this->privates['fos_user.resetting.form.factory'] = new \FOS\UserBundle\Form\Factory\FormFactory(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), 'fos_user_resetting_form', 'FOS\\UserBundle\\Form\\Type\\ResettingFormType', $this->parameters['fos_user.resetting.form.validation_groups']);
