<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.form_factory.delete_comment' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/FormFactory/DeleteCommentFormFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/FormFactory/DeleteCommentFormFactory.php';

return $this->services['fos_comment.form_factory.delete_comment'] = new \FOS\CommentBundle\FormFactory\DeleteCommentFormFactory(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), 'FOS\\CommentBundle\\Form\\DeleteCommentType', 'fos_comment_delete_comment');
