<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.manager.thread' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Model/ThreadManagerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Acl/AclThreadManager.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Model/ThreadManager.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Entity/ThreadManager.php';

return $this->services['fos_comment.manager.thread'] = new \FOS\CommentBundle\Acl\AclThreadManager(new \FOS\CommentBundle\Entity\ThreadManager(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['fos_comment.entity_manager'] ?? $this->load('getFosComment_EntityManagerService.php')), 'App\\Entity\\Thread'), ($this->services['fos_comment.acl.thread'] ?? $this->getFosComment_Acl_ThreadService()));
