<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.form_factory.commentable_thread' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/FormFactory/CommentableThreadFormFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/FormFactory/CommentableThreadFormFactory.php';

return $this->services['fos_comment.form_factory.commentable_thread'] = new \FOS\CommentBundle\FormFactory\CommentableThreadFormFactory(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), 'FOS\\CommentBundle\\Form\\CommentableThreadType', 'fos_comment_commentable_thread');
