<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.mailer.twig_swift' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Mailer/MailerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Mailer/TwigSwiftMailer.php';

return $this->privates['fos_user.mailer.twig_swift'] = new \FOS\UserBundle\Mailer\TwigSwiftMailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['twig'] ?? $this->getTwigService()), ['template' => ['confirmation' => 'bundles/FOSUserBundle/Registration/email.html.twig', 'resetting' => 'bundles/FOSUserBundle/Resetting/email.html.twig'], 'from_email' => ['confirmation' => $this->getParameter('fos_user.registration.confirmation.from_email'), 'resetting' => $this->getParameter('fos_user.resetting.email.from_email')]]);
