<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_user.change_password.controller' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Controller/ChangePasswordController.php';

$this->services['fos_user.change_password.controller'] = $instance = new \FOS\UserBundle\Controller\ChangePasswordController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['fos_user.change_password.form.factory'] ?? $this->load('getFosUser_ChangePassword_Form_FactoryService.php')), ($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')));

$instance->setContainer($this);

return $instance;
