<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.manager.vote' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Model/VoteManagerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Acl/AclVoteManager.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Model/VoteManager.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/Entity/VoteManager.php';

return $this->services['fos_comment.manager.vote'] = new \FOS\CommentBundle\Acl\AclVoteManager(new \FOS\CommentBundle\Entity\VoteManager(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['fos_comment.entity_manager'] ?? $this->load('getFosComment_EntityManagerService.php')), 'App\\Entity\\Vote'), ($this->services['fos_comment.acl.vote'] ?? $this->getFosComment_Acl_VoteService()), ($this->services['fos_comment.acl.comment'] ?? $this->getFosComment_Acl_CommentService()));
