<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_comment.listener.thread_counters' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/comment-bundle/EventListener/ThreadCountersListener.php';

return $this->privates['fos_comment.listener.thread_counters'] = new \FOS\CommentBundle\EventListener\ThreadCountersListener(($this->services['fos_comment.manager.comment'] ?? $this->load('getFosComment_Manager_CommentService.php')));
