<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.listener.email_confirmation' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/EventListener/EmailConfirmationListener.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGeneratorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGenerator.php';

return $this->privates['fos_user.listener.email_confirmation'] = new \FOS\UserBundle\EventListener\EmailConfirmationListener(($this->privates['fos_user.mailer.twig_swift'] ?? $this->load('getFosUser_Mailer_TwigSwiftService.php')), ($this->privates['fos_user.util.token_generator.default'] ?? ($this->privates['fos_user.util.token_generator.default'] = new \FOS\UserBundle\Util\TokenGenerator())), ($this->services['router'] ?? $this->getRouterService()), ($this->services['session'] ?? $this->load('getSessionService.php')));
