<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'httplug.stream_factory' shared service.

include_once \dirname(__DIR__, 4).'/vendor/php-http/message-factory/src/StreamFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/StreamFactoryDiscovery.php';

return $this->services['httplug.stream_factory'] = \Http\Discovery\StreamFactoryDiscovery::find();
