<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.registration.form.handler' shared service.

include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Form/RegistrationFormHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Form/FOSUBRegistrationFormHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGeneratorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGenerator.php';

$this->services['hwi_oauth.registration.form.handler'] = $instance = new \HWI\Bundle\OAuthBundle\Form\FOSUBRegistrationFormHandler(($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')), ($this->privates['fos_user.mailer.twig_swift'] ?? $this->load('getFosUser_Mailer_TwigSwiftService.php')), ($this->privates['fos_user.util.token_generator.default'] ?? ($this->privates['fos_user.util.token_generator.default'] = new \FOS\UserBundle\Util\TokenGenerator())), 30);

$instance->setFormHandler(NULL);

return $instance;
