<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.http_client' shared service.

include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/HttpMethodsClient.php';

return $this->services['hwi_oauth.http_client'] = new \Http\Client\Common\HttpMethodsClient(($this->services['httplug.client'] ?? $this->load('getHttplug_ClientService.php')), ($this->services['httplug.message_factory'] ?? $this->load('getHttplug_MessageFactoryService.php')));
