<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_translation.config_factory' shared service.

include_once \dirname(__DIR__, 4).'/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/ConfigFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/jms/translation-bundle/JMS/TranslationBundle/Translation/ConfigBuilder.php';

$a = new \JMS\TranslationBundle\Translation\ConfigBuilder();
$a->setTranslationsDir((\dirname(__DIR__, 4).'/translations'));
$a->setScanDirs([0 => (\dirname(__DIR__, 4).'/templates'), 1 => (\dirname(__DIR__, 4).'/src')]);
$a->setIgnoredDomains([]);
$a->setDomains([]);
$a->setEnabledExtractors([]);
$a->setExcludedDirs([]);
$a->setExcludedNames([0 => '*TestCase.php', 1 => '*Test.php']);
$a->setOutputFormat('xliff');
$a->setKeepOldTranslations(true);
$a->setLoadResources([]);

return $this->services['jms_translation.config_factory'] = new \JMS\TranslationBundle\Translation\ConfigFactory(['app' => $a]);
