<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'payum.dynamic_gateways.config_storage' shared service.

include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Storage/StorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Storage/CryptoStorageDecorator.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Storage/AbstractStorage.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Bridge/Doctrine/Storage/DoctrineStorage.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Security/CypherInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Bridge/Defuse/Security/DefuseCypher.php';

return $this->services['payum.dynamic_gateways.config_storage'] = new \Payum\Core\Storage\CryptoStorageDecorator(new \Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'App\\Entity\\PaymentGateway'), ($this->privates['payum.dynamic_gateways.cypher'] ?? ($this->privates['payum.dynamic_gateways.cypher'] = new \Payum\Core\Bridge\Defuse\Security\DefuseCypher($this->getEnv('PAYUM_CYPHER_KEY')))));
