<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'presta_sitemap.dump_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/presta/sitemap-bundle/Command/DumpSitemapsCommand.php';

$this->services['presta_sitemap.dump_command'] = $instance = new \Presta\SitemapBundle\Command\DumpSitemapsCommand(($this->services['router'] ?? $this->getRouterService()), ($this->services['presta_sitemap.dumper'] ?? $this->load('getPrestaSitemap_DumperService.php')), 'public');

$instance->setName('presta:sitemaps:dump');

return $instance;
