<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Dashboard\Shared\PayoutRequestController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/src/Controller/Dashboard/Shared/PayoutRequestController.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Security/CypherInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Bridge/Defuse/Security/DefuseCypher.php';

return $this->services['App\\Controller\\Dashboard\\Shared\\PayoutRequestController'] = new \App\Controller\Dashboard\Shared\PayoutRequestController(($this->privates['payum.dynamic_gateways.cypher'] ?? ($this->privates['payum.dynamic_gateways.cypher'] = new \Payum\Core\Bridge\Defuse\Security\DefuseCypher($this->getEnv('PAYUM_CYPHER_KEY')))));
