<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\bundles\FOSUserBundle\RegistrationController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/src/Controller/bundles/FOSUserBundle/RegistrationController.php';

return $this->services['App\\Controller\\bundles\\FOSUserBundle\\RegistrationController'] = new \App\Controller\bundles\FOSUserBundle\RegistrationController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['hwi_oauth.registration.form.factory'] ?? $this->load('getHwiOauth_Registration_Form_FactoryService.php')), ($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')), ($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->privates['App\\Service\\AppServices'] ?? $this->getAppServicesService()));
