<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\bundles\FOSUserBundle\ResettingController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/src/Controller/bundles/FOSUserBundle/ResettingController.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Mailer/MailerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Mailer/Mailer.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGeneratorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/user-bundle/Util/TokenGenerator.php';

return $this->services['App\\Controller\\bundles\\FOSUserBundle\\ResettingController'] = new \App\Controller\bundles\FOSUserBundle\ResettingController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['fos_user.resetting.form.factory'] ?? $this->load('getFosUser_Resetting_Form_FactoryService.php')), ($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')), ($this->privates['fos_user.util.token_generator.default'] ?? ($this->privates['fos_user.util.token_generator.default'] = new \FOS\UserBundle\Util\TokenGenerator())), new \FOS\UserBundle\Mailer\Mailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), ['confirmation.template' => 'bundles/FOSUserBundle/Registration/email.html.twig', 'resetting.template' => 'bundles/FOSUserBundle/Resetting/email.html.twig', 'from_email' => ['confirmation' => $this->getParameter('fos_user.registration.confirmation.from_email'), 'resetting' => $this->getParameter('fos_user.resetting.email.from_email')]]), NULL);
