<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Debril\RssAtomBundle\Controller\StreamController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Controller/StreamController.php';

return $this->services['Debril\\RssAtomBundle\\Controller\\StreamController'] = new \Debril\RssAtomBundle\Controller\StreamController();
