<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMapInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMap.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/signin$'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/signup/attendee'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/signup/organizer'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/resetting'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/dashboard/administrator'), [0 => 'ROLE_ADMINISTRATOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/_trans/'), [0 => 'ROLE_ADMINISTRATOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/_console'), [0 => 'ROLE_ADMINISTRATOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/dashboard/organizer'), [0 => 'ROLE_ORGANIZER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/dashboard/attendee'), [0 => 'ROLE_ATTENDEE'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/dashboard/scanner'), [0 => 'ROLE_SCANNER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^(.*?)/dashboard/pointofsale'), [0 => 'ROLE_POINTOFSALE'], NULL);

return $instance;
