<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'JMS\TranslationBundle\Controller\TranslateController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/jms/translation-bundle/JMS/TranslationBundle/Controller/TranslateController.php';

return $this->services['JMS\\TranslationBundle\\Controller\\TranslateController'] = new \JMS\TranslationBundle\Controller\TranslateController(($this->services['jms_translation.config_factory'] ?? $this->load('getJmsTranslation_ConfigFactoryService.php')), ($this->privates['jms_translation.loader_manager'] ?? $this->load('getJmsTranslation_LoaderManagerService.php')));
