<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.list_synchronizer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Subscriber/ListSynchronizer.php';

return $this->services['welp_mailchimp.list_synchronizer'] = new \Welp\MailchimpBundle\Subscriber\ListSynchronizer(($this->services['welp_mailchimp.list_repository'] ?? $this->load('getWelpMailchimp_ListRepositoryService.php')));
