<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.list_repository' shared service.

include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Subscriber/ListRepository.php';
include_once \dirname(__DIR__, 4).'/vendor/drewm/mailchimp-api/src/MailChimp.php';

return $this->services['welp_mailchimp.list_repository'] = new \Welp\MailchimpBundle\Subscriber\ListRepository(($this->services['welp_mailchimp.mailchimp_master'] ?? ($this->services['welp_mailchimp.mailchimp_master'] = new \DrewM\MailChimp\MailChimp('542673602536197ee271b0d4d78164da-us20'))));
