<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'welp_mailchimp.subscriber_listener' shared service.

include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Event/SubscriberListener.php';

return $this->privates['welp_mailchimp.subscriber_listener'] = new \Welp\MailchimpBundle\Event\SubscriberListener(($this->services['welp_mailchimp.list_repository'] ?? $this->load('getWelpMailchimp_ListRepositoryService.php')));
