<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'welp_mailchimp.command.webhook' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Command/WebhookCommand.php';

$this->privates['welp_mailchimp.command.webhook'] = $instance = new \Welp\MailchimpBundle\Command\WebhookCommand(($this->services['welp_mailchimp.list_provider'] ?? $this->load('getWelpMailchimp_ListProviderService.php')), ($this->services['welp_mailchimp.list_repository'] ?? $this->load('getWelpMailchimp_ListRepositoryService.php')));

$instance->setName('welp:mailchimp:webhook');

return $instance;
