<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.list_provider' shared service.

include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Provider/ListProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/welp/mailchimp-bundle/src/Provider/ConfigListProvider.php';

return $this->services['welp_mailchimp.list_provider'] = new \Welp\MailchimpBundle\Provider\ConfigListProvider(($this->services['welp_mailchimp.provider.factory'] ?? $this->load('getWelpMailchimp_Provider_FactoryService.php')), $this->parameters['welp_mailchimp.lists']);
