<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EventDate extends \App\Entity\EventDate implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'event', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'online', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'venue', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'tickets', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'scanners', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'pointofsales', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'payoutRequests', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'active', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'startdate', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'enddate'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'event', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'online', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'venue', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'tickets', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'scanners', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'pointofsales', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'payoutRequests', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'active', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'startdate', '' . "\0" . 'App\\Entity\\EventDate' . "\0" . 'enddate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EventDate $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function payoutRequested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'payoutRequested', []);

        return parent::payoutRequested();
    }

    /**
     * {@inheritDoc}
     */
    public function payoutRequestStatusClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'payoutRequestStatusClass', []);

        return parent::payoutRequestStatusClass();
    }

    /**
     * {@inheritDoc}
     */
    public function payoutRequestStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'payoutRequestStatus', []);

        return parent::payoutRequestStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function canBeScannedBy($scanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canBeScannedBy', [$scanner]);

        return parent::canBeScannedBy($scanner);
    }

    /**
     * {@inheritDoc}
     */
    public function isOnSaleByPos($pointOfSale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOnSaleByPos', [$pointOfSale]);

        return parent::isOnSaleByPos($pointOfSale);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCheckInPercentage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCheckInPercentage', []);

        return parent::getTotalCheckInPercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function getScannedTicketsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScannedTicketsCount', []);

        return parent::getScannedTicketsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSalesPercentage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSalesPercentage', []);

        return parent::getTotalSalesPercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketsQuantitySum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketsQuantitySum', []);

        return parent::getTicketsQuantitySum();
    }

    /**
     * {@inheritDoc}
     */
    public function getSales($role = 'all', $user = 'all', $formattedForPayoutApproval = false, $includeFees = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSales', [$role, $user, $formattedForPayoutApproval, $includeFees]);

        return parent::getSales($role, $user, $formattedForPayoutApproval, $includeFees);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTicketFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTicketFees', []);

        return parent::getTotalTicketFees();
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketPricePercentageCutSum($role = 'all')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketPricePercentageCutSum', [$role]);

        return parent::getTicketPricePercentageCutSum($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizerPayoutAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizerPayoutAmount', []);

        return parent::getOrganizerPayoutAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function displayPosNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'displayPosNames', []);

        return parent::displayPosNames();
    }

    /**
     * {@inheritDoc}
     */
    public function displayScannersNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'displayScannersNames', []);

        return parent::displayScannersNames();
    }

    /**
     * {@inheritDoc}
     */
    public function generateReference($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateReference', [$length]);

        return parent::generateReference($length);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderElementsQuantitySum($status = 1, $user = 'all', $role = 'all')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderElementsQuantitySum', [$status, $user, $role]);

        return parent::getOrderElementsQuantitySum($status, $user, $role);
    }

    /**
     * {@inheritDoc}
     */
    public function isSoldOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSoldOut', []);

        return parent::isSoldOut();
    }

    /**
     * {@inheritDoc}
     */
    public function hasATicketOnSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasATicketOnSale', []);

        return parent::hasATicketOnSale();
    }

    /**
     * {@inheritDoc}
     */
    public function isOnSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOnSale', []);

        return parent::isOnSale();
    }

    /**
     * {@inheritDoc}
     */
    public function stringifyStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stringifyStatus', []);

        return parent::stringifyStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function stringifyStatusClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stringifyStatusClass', []);

        return parent::stringifyStatusClass();
    }

    /**
     * {@inheritDoc}
     */
    public function isFree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFree', []);

        return parent::isFree();
    }

    /**
     * {@inheritDoc}
     */
    public function getCheapestTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheapestTicket', []);

        return parent::getCheapestTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function getVenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVenue', []);

        return parent::getVenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setVenue($venue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVenue', [$venue]);

        return parent::setVenue($venue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTickets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTickets', []);

        return parent::getTickets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTicket($ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTicket', [$ticket]);

        return parent::addTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTicket($ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTicket', [$ticket]);

        return parent::removeTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getScanners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScanners', []);

        return parent::getScanners();
    }

    /**
     * {@inheritDoc}
     */
    public function addScanner($scanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScanner', [$scanner]);

        return parent::addScanner($scanner);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScanner($scanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScanner', [$scanner]);

        return parent::removeScanner($scanner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointofsales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointofsales', []);

        return parent::getPointofsales();
    }

    /**
     * {@inheritDoc}
     */
    public function addPointofsale($pointofsale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPointofsale', [$pointofsale]);

        return parent::addPointofsale($pointofsale);
    }

    /**
     * {@inheritDoc}
     */
    public function removePointofsale($pointofsale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePointofsale', [$pointofsale]);

        return parent::removePointofsale($pointofsale);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartdate', []);

        return parent::getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartdate($startdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartdate', [$startdate]);

        return parent::setStartdate($startdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnddate', []);

        return parent::getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnddate($enddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnddate', [$enddate]);

        return parent::setEnddate($enddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', []);

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent', [$event]);

        return parent::setEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnline', []);

        return parent::getOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnline($online)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnline', [$online]);

        return parent::setOnline($online);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayoutRequests()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayoutRequests', []);

        return parent::getPayoutRequests();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayoutRequest($payoutRequest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayoutRequest', [$payoutRequest]);

        return parent::addPayoutRequest($payoutRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayoutRequest($payoutRequest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayoutRequest', [$payoutRequest]);

        return parent::removePayoutRequest($payoutRequest);
    }

}
