<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentGateway extends \App\Entity\PaymentGateway implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'payoutRequests', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'organizer', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'name', 'slug', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'gatewayLogoName', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'gatewayLogoFile', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'number', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'updatedAt', 'factoryName', 'gatewayName', 'config', 'decryptedConfig'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'payoutRequests', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'organizer', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'name', 'slug', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'gatewayLogoName', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'gatewayLogoFile', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'number', '' . "\0" . 'App\\Entity\\PaymentGateway' . "\0" . 'updatedAt', 'factoryName', 'gatewayName', 'config', 'decryptedConfig'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaymentGateway $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function decrypt(\Payum\Core\Security\CypherInterface $cypher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decrypt', [$cypher]);

        return parent::decrypt($cypher);
    }

    /**
     * {@inheritDoc}
     */
    public function encrypt(\Payum\Core\Security\CypherInterface $cypher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encrypt', [$cypher]);

        return parent::encrypt($cypher);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogoPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogoPath', []);

        return parent::getLogoPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setGatewayLogoFile(\Symfony\Component\HttpFoundation\File\File $imageFile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGatewayLogoFile', [$imageFile]);

        return parent::setGatewayLogoFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getGatewayLogoFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGatewayLogoFile', []);

        return parent::getGatewayLogoFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getGatewayLogoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGatewayLogoName', []);

        return parent::getGatewayLogoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGatewayLogoName($gatewayLogoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGatewayLogoName', [$gatewayLogoName]);

        return parent::setGatewayLogoName($gatewayLogoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayoutRequests()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayoutRequests', []);

        return parent::getPayoutRequests();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayoutRequest($payoutRequest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayoutRequest', [$payoutRequest]);

        return parent::addPayoutRequest($payoutRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayoutRequest($payoutRequest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayoutRequest', [$payoutRequest]);

        return parent::removePayoutRequest($payoutRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizer', []);

        return parent::getOrganizer();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizer($organizer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizer', [$organizer]);

        return parent::setOrganizer($organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactoryName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactoryName', []);

        return parent::getFactoryName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactoryName($factoryName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactoryName', [$factoryName]);

        return parent::setFactoryName($factoryName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGatewayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGatewayName', []);

        return parent::getGatewayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGatewayName($gatewayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGatewayName', [$gatewayName]);

        return parent::setGatewayName($gatewayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfig', []);

        return parent::getConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfig(array $config)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfig', [$config]);

        return parent::setConfig($config);
    }

}
