<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HomepageHeroSettings extends \App\Entity\HomepageHeroSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'id', 'translations', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'content', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'events', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'organizers', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundFile', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundName', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundSize', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundMimeType', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundOriginalName', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundDimensions', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'show_search_box', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'updatedAt', 'newTranslations', 'currentLocale', 'defaultLocale'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'id', 'translations', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'content', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'events', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'organizers', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundFile', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundName', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundSize', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundMimeType', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundOriginalName', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'customBackgroundDimensions', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'show_search_box', '' . "\0" . 'App\\Entity\\HomepageHeroSettings' . "\0" . 'updatedAt', 'newTranslations', 'currentLocale', 'defaultLocale'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HomepageHeroSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function clearEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearEvents', []);

        return parent::clearEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $arguments]);

        return parent::__call($method, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundFile(\Symfony\Component\HttpFoundation\File\File $customBackgroundFile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundFile', [$customBackgroundFile]);

        return parent::setCustomBackgroundFile($customBackgroundFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundFile', []);

        return parent::getCustomBackgroundFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundPath', []);

        return parent::getCustomBackgroundPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundName', []);

        return parent::getCustomBackgroundName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundName($customBackgroundName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundName', [$customBackgroundName]);

        return parent::setCustomBackgroundName($customBackgroundName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundSize', []);

        return parent::getCustomBackgroundSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundSize($customBackgroundSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundSize', [$customBackgroundSize]);

        return parent::setCustomBackgroundSize($customBackgroundSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundMimeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundMimeType', []);

        return parent::getCustomBackgroundMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundMimeType($customBackgroundMimeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundMimeType', [$customBackgroundMimeType]);

        return parent::setCustomBackgroundMimeType($customBackgroundMimeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundOriginalName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundOriginalName', []);

        return parent::getCustomBackgroundOriginalName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundOriginalName($customBackgroundOriginalName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundOriginalName', [$customBackgroundOriginalName]);

        return parent::setCustomBackgroundOriginalName($customBackgroundOriginalName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomBackgroundDimensions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomBackgroundDimensions', []);

        return parent::getCustomBackgroundDimensions();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomBackgroundDimensions($customBackgroundDimensions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomBackgroundDimensions', [$customBackgroundDimensions]);

        return parent::setCustomBackgroundDimensions($customBackgroundDimensions);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', []);

        return parent::getEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent', [$event]);

        return parent::addEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvent', [$event]);

        return parent::removeEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowSearchBox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowSearchBox', []);

        return parent::getShowSearchBox();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowSearchBox($show_search_box)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowSearchBox', [$show_search_box]);

        return parent::setShowSearchBox($show_search_box);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizers', []);

        return parent::getOrganizers();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrganizer($organizer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrganizer', [$organizer]);

        return parent::addOrganizer($organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrganizer($organizer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrganizer', [$organizer]);

        return parent::removeOrganizer($organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', []);

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewTranslations', []);

        return parent::getNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', [$translation]);

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', [$translation]);

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL, $fallbackToDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', [$locale, $fallbackToDefault]);

        return parent::translate($locale, $fallbackToDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function mergeNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeNewTranslations', []);

        return parent::mergeNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', [$locale]);

        return parent::setCurrentLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', []);

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocale', [$locale]);

        return parent::setDefaultLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocale', []);

        return parent::getDefaultLocale();
    }

}
