<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venue extends \App\Entity\Venue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'id', 'translations', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'eventdates', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'organizer', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'amenities', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'seatedguests', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'standingguests', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'neighborhoods', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'foodbeverage', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'pricing', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'availibility', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'hidden', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'showmap', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'quoteform', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'street2', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'state', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'postalcode', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'lat', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'lng', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'listedondirectory', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'contactemail', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'deletedAt', 'newTranslations', 'currentLocale', 'defaultLocale'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'id', 'translations', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'eventdates', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'organizer', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'amenities', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'seatedguests', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'standingguests', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'neighborhoods', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'foodbeverage', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'pricing', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'availibility', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'hidden', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'showmap', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'quoteform', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'street', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'street2', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'state', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'postalcode', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'lat', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'lng', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'listedondirectory', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'contactemail', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Venue' . "\0" . 'deletedAt', 'newTranslations', 'currentLocale', 'defaultLocale'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __call($method, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $arguments]);

        return parent::__call($method, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function stringifyAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stringifyAddress', []);

        return parent::stringifyAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHidden', []);

        return parent::getHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function setHidden($hidden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHidden', [$hidden]);

        return parent::setHidden($hidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getListedondirectory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListedondirectory', []);

        return parent::getListedondirectory();
    }

    /**
     * {@inheritDoc}
     */
    public function setListedondirectory($listedondirectory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListedondirectory', [$listedondirectory]);

        return parent::setListedondirectory($listedondirectory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowmap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowmap', []);

        return parent::getShowmap();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowmap($showmap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowmap', [$showmap]);

        return parent::setShowmap($showmap);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet2', []);

        return parent::getStreet2();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet2($street2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet2', [$street2]);

        return parent::setStreet2($street2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalcode', []);

        return parent::getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalcode($postalcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalcode', [$postalcode]);

        return parent::setPostalcode($postalcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmenities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmenities', []);

        return parent::getAmenities();
    }

    /**
     * {@inheritDoc}
     */
    public function addAmenity($amenity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAmenity', [$amenity]);

        return parent::addAmenity($amenity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAmenity($amenity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAmenity', [$amenity]);

        return parent::removeAmenity($amenity);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatedguests()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatedguests', []);

        return parent::getSeatedguests();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatedguests($seatedguests)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatedguests', [$seatedguests]);

        return parent::setSeatedguests($seatedguests);
    }

    /**
     * {@inheritDoc}
     */
    public function getStandingguests()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStandingguests', []);

        return parent::getStandingguests();
    }

    /**
     * {@inheritDoc}
     */
    public function setStandingguests($standingguests)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStandingguests', [$standingguests]);

        return parent::setStandingguests($standingguests);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeighborhoods()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeighborhoods', []);

        return parent::getNeighborhoods();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeighborhoods($neighborhoods)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeighborhoods', [$neighborhoods]);

        return parent::setNeighborhoods($neighborhoods);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricing', []);

        return parent::getPricing();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricing($pricing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricing', [$pricing]);

        return parent::setPricing($pricing);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailibility()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailibility', []);

        return parent::getAvailibility();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailibility($availibility)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailibility', [$availibility]);

        return parent::setAvailibility($availibility);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoodbeverage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoodbeverage', []);

        return parent::getFoodbeverage();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoodbeverage($foodbeverage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoodbeverage', [$foodbeverage]);

        return parent::setFoodbeverage($foodbeverage);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePlaceholder($size = 'default')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePlaceholder', [$size]);

        return parent::getImagePlaceholder($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstImageOrPlaceholder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstImageOrPlaceholder', []);

        return parent::getFirstImageOrPlaceholder();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizer', []);

        return parent::getOrganizer();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizer($organizer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizer', [$organizer]);

        return parent::setOrganizer($organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventdates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventdates', []);

        return parent::getEventdates();
    }

    /**
     * {@inheritDoc}
     */
    public function addEventdate($eventdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEventdate', [$eventdate]);

        return parent::addEventdate($eventdate);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEventdate($eventdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEventdate', [$eventdate]);

        return parent::removeEventdate($eventdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactemail', []);

        return parent::getContactemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactemail($contactemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactemail', [$contactemail]);

        return parent::setContactemail($contactemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuoteform()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuoteform', []);

        return parent::getQuoteform();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuoteform($quoteform)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuoteform', [$quoteform]);

        return parent::setQuoteform($quoteform);
    }

    /**
     * {@inheritDoc}
     */
    public function getLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', []);

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function setLat($lat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', [$lat]);

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLng', []);

        return parent::getLng();
    }

    /**
     * {@inheritDoc}
     */
    public function setLng($lng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLng', [$lng]);

        return parent::setLng($lng);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', []);

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewTranslations', []);

        return parent::getNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', [$translation]);

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', [$translation]);

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL, $fallbackToDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', [$locale, $fallbackToDefault]);

        return parent::translate($locale, $fallbackToDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function mergeNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeNewTranslations', []);

        return parent::mergeNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', [$locale]);

        return parent::setCurrentLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', []);

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocale', [$locale]);

        return parent::setDefaultLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocale', []);

        return parent::getDefaultLocale();
    }

}
