<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'orderelements', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'paymentgateway', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'payment', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'ticketFee', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'ticketPricePercentageCut', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'currencyCcy', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'currencySymbol', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'deletedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'orderelements', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'paymentgateway', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'payment', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'ticketFee', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'ticketPricePercentageCut', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'currencyCcy', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'currencySymbol', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'deletedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function containsEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'containsEvent', [$event]);

        return parent::containsEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusClass', []);

        return parent::getStatusClass();
    }

    /**
     * {@inheritDoc}
     */
    public function stringifyStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'stringifyStatus', []);

        return parent::stringifyStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatusClass($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatusClass', [$status]);

        return parent::getPaymentStatusClass($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderElementsQuantitySum($status = 'all', $organizer = 'all')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderElementsQuantitySum', [$status, $organizer]);

        return parent::getOrderElementsQuantitySum($status, $organizer);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderElementsPriceSum($includeFees = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderElementsPriceSum', [$includeFees]);

        return parent::getOrderElementsPriceSum($includeFees);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTicketFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTicketFees', []);

        return parent::getTotalTicketFees();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalFees', []);

        return parent::getTotalFees();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotFreeOrderElementsQuantitySum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotFreeOrderElementsQuantitySum', []);

        return parent::getNotFreeOrderElementsQuantitySum();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderelements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderelements', []);

        return parent::getOrderelements();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderelement($orderelement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderelement', [$orderelement]);

        return parent::addOrderelement($orderelement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderelement($orderelement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderelement', [$orderelement]);

        return parent::removeOrderelement($orderelement);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentgateway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentgateway', []);

        return parent::getPaymentgateway();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentgateway($paymentgateway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentgateway', [$paymentgateway]);

        return parent::setPaymentgateway($paymentgateway);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayment', []);

        return parent::getPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayment($payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayment', [$payment]);

        return parent::setPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketFee', []);

        return parent::getTicketFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketFee($ticketFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketFee', [$ticketFee]);

        return parent::setTicketFee($ticketFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyCcy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyCcy', []);

        return parent::getCurrencyCcy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyCcy($currencyCcy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyCcy', [$currencyCcy]);

        return parent::setCurrencyCcy($currencyCcy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencySymbol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencySymbol', []);

        return parent::getCurrencySymbol();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencySymbol($currencySymbol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencySymbol', [$currencySymbol]);

        return parent::setCurrencySymbol($currencySymbol);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketPricePercentageCut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketPricePercentageCut', []);

        return parent::getTicketPricePercentageCut();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketPricePercentageCut($ticketPricePercentageCut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketPricePercentageCut', [$ticketPricePercentageCut]);

        return parent::setTicketPricePercentageCut($ticketPricePercentageCut);
    }

}
